### ISSUE TITLE
Config values in dxl_init.yaml for other motors

### ISSUE THREAD

**Issue by rohit-murthy** [ROBOTIS-GIT/ROBOTIS-MANIPULATOR#2]
I'm using the M54-60-S250-R, L54-50-S290-R motors alongwith the prescribed H54, H42 motors. I haven't been able to find the corresponding values mentioned in dxl_init.yaml for the other motors. Do you know where they might be available?

**Comment by s-changhyun** [comment]
If you use another motor in Manipulator, you have to change the dxl_init.yaml. 
The value is metioned in ROBOTIS-Framework/robotis_device/devices/dynamixel/.
If there is no device file, you have to add device file that can be mentioned in http://support.robotis.com/en/.
