### ISSUE TITLE
Using torque control for the manipulator

### ISSUE THREAD

**Issue by rohit-murthy** [ROBOTIS-GIT/ROBOTIS-MANIPULATOR#3]
I'm trying to use Torque Control for the motors in the manipulator, I've gone through the code and it seems like the variable control_mode needs to be defined to either position, velocity or torque control. In RobotisController.cpp, you subscribed to the topic /robotis/setCtrlMode but there is no publisher. Where is the manipulator getting the information to run as Position Control (or is it default)? 
Do I need to write a publisher to send a message saying that I want to run in Torque Control?
And how will the GUI inputs work when I enter Torque Control, as in will giving the joint angles work or will only the kinematic pose operate on the manipulator?

**Comment by s-changhyun** [comment]
We have a plan to support Torque Control in ROS Framework. Currently, the manipulator_manager is set default as Position Control. About GUI, if you want to work with Torque Control, you have to create GUI yourself.

**Comment by rohit-murthy** [comment]
Ahh, okay now I get it.
In the GUI, is sending the pose enough to make the manipulator move to that point? And which origin does this coordinate have to be defined with respect to?

**Comment by s-changhyun** [comment]
Currently, if you send the pose, base_module create minimum jerk profile and send to the robot.
The origin is /world in urdf file.

**Comment by rohit-murthy** [comment]
Thanks! 
I had some doubts related to the robotis_manipulator.xacro file. 
-Each link and joint has an origin defined: is this the origin as defined in the stl file or the centre of mass of the link/joint or some other point? 
-It appears that the origin defined is not wrt the world frame but wrt the previous link or joint, am I correct?
-Am I correct in assuming that the origins have been defined for the initial pose?
-What units are the velocity limits in?

**Comment by s-changhyun** [comment]
You can get more information from this page.
http://wiki.ros.org/urdf/XML/model
