### ISSUE TITLE
Values given in ManipulatorKinematicsDynamics.cpp 

### ISSUE THREAD

**Issue by rohit-murthy** [ROBOTIS-GIT/ROBOTIS-MANIPULATOR#4]
Hi, please can you clarify what the values mentioned at the start of the ManipulatorKinematicsDynamics.cpp represent? 
-Which point does the relative_position describe and with respect to what co-ordinate frame? 
-Is the joint axis mentioned wrt its own co-ordinate system or the global coordinate system?
-The mass mentioned is of the motor + frame mass that comes after?
-How come the CoM is zero for all motors? Is the origin of the coordinate system located at the CoM or is it made zero because it is not considered relevant for the calculations? 

Please can you assist me in these queries as this will go a long way in helping me understand your code. Moreover, since this is specific to Robotis, I believe you'll are the only people who will be able to explain this. Thank you.

**Comment by s-changhyun** [comment]
Every information what you want is as same as URDF file.
You can visualize the model in Rviz.

**Comment by rohit-murthy** [comment]
Thanks for that information. But I'm now confused as how the inverse kinematics algorithms are working because isn't the DH convention usually followed for that? As far as I can see the URDF doesn't follow that format. 
Also, how does the robot understand where the global origin is?

**Comment by s-changhyun** [comment]
If you want to know about inverse kinematics algorithm in ManipulatorKinematicsDynamics.cpp,
this book (https://books.google.co.kr/books?id=guIkBAAAQBAJ&pg=PA47&lpg=PA47&dq=forward+kinematics,+kajita&source=bl&ots=6We6J_mv3h&sig=33bXCAvbjl6w9HA4keiRp3JM5iw&hl=ko&sa=X&ved=0ahUKEwig8aPv18fNAhXFHpQKHR-IDP4Q6AEIWjAG#v=onepage&q=forward%20kinematics%2C%20kajita&f=false) will be helpful.

**Comment by rohit-murthy** [comment]
Thank you for that link, it was very considerate of you. But my doubt is that, in URDF the axes for a particular link/joint depends on the coordinate system in the CAD model. Whereas in the DH convention, the joint axis is always considered as z axis. Because when I created my URDF I had a lot of problems and repeatedly had to change the orientation of the axes while the URDF provided in the robotics code shows no such change in any visual elements. 

I'm sorry, I know that these seem like very basic doubts. I'll try to implement your suggestions asap.

**Comment by s-changhyun** [comment]
As you already know, it is important to set the axis hen you create STL file for URDF.
About the DH convention of ROBOTIS MANIPULATOR, this SDK will be hulpful (http://en.robotis.com/BlueAD/board.php?bbs_id=downloads&mode=view&bbs_no=1152543&page=1&key=&keyword=&sort=&scate=).  
But, this code is not created in ROS, probably it will work on only Windows.

**Comment by rohit-murthy** [comment]
Thanks. So if I've understood correctly, if I get my URDF correct and similar to how the robotis URDF looks, then my inverse kinematics should also work correctly? 
A doubt regarding your CAD, where is the origin defined? And the axes are aligned, I guess, with z axis along the joint, x axis coming out of the plane and y axis according to the right hand rule?

**Comment by rohit-murthy** [comment]
Actually, I had a look at the CAD files provided by Robotis and it looks like the origin is selected at the point of contact between a motor and the next frame. Eg., the origin of link_2 is at the contact between motor1 and the frame attached to motor2. And the axes are oriented in accordance with the global coordinate system. Are these inferences of mine correct?

**Comment by rohit-murthy** [comment]
Hi, I've made by URDF and it looks correct. When I run the manipulator code, the forward kinematics is very accurate but the inverse kinematics is not working properly. 

I have attached a couple of photos and a short video of the IK failing. I understand that this is asking a lot but please check it out if you have time: [Click Here](https://drive.google.com/open?id=0B4RAT4cwHmB8ZlJyZV9fSmRlN00)

Git.jpg shows the initial pose of the arm
Rviz Screenshot.png shows the URDF in rviz which matches with the initial pose of the arm
Target.jpg shows the target pose that inputting into the GUI
IK Fail.mp4 is the short video showing the dangerously high speed of some of the motors before failing.

**Comment by s-changhyun** [comment]
In my opinion, you have to consider the singularity when you solve the inverse kinematics equations.

**Comment by s-changhyun** [comment]
In Rviz, you can confirm origin axis of each joint from the tf

**Comment by rohit-murthy** [comment]
Do singularities not occur with the Robotis Manipulator?

**Comment by s-changhyun** [comment]
Of course, there is a singularity in every robots.
That's why we set an initial pose in ROBOTIS MANIPULATOR.
Please, look the process function in thormang3_manipulation_module/src/ManipulationModule.cpp more precisely.
Also, you should take into account that we cannot support entire code and algorithm.
